### ISSUE TITLE
Organización

### ISSUE THREAD

**Issue by runobe** [opencitydata/vocab-sector-publico-subvenciones#10]
En el modelo de datos se tienen los campos área, entidad financiadora, servicio y organización en el ejemplo de visualización la entidad_financiadora coincide con el área.
En el modelo de datos de Zaragoza tenemos servicio, organo_gestor que lo podemos mapear para entidad financiadora (son concejalías principalmente) pero ¿para organización que se espera? (ayuntamiento, sociedades…)

**Comment by ocorcho** [comment]
Las cinco (no cuatro) relaciones son distintos roles que puede tener cualquier tipo de organización en el contexto de las convocatorias de subvenciones y las concesiones de subvenciones:
* entidadFinanciadora (para Convocatoria)
* área (para Convocatoria)
* servicio (para Convocatoria)
* gestionadoPor (para Convocatoria)
* tieneBeneficiario (para Concesión)
Se han tenido en cuenta las cuatro propiedades aplicables a la Convocatoria porque aparecieron en los requisitos como posibles relaciones que podrían tener distintos valores. Es posible que en algún caso los datos que estéis recogiendo hasta el momento no sean tan detallados, o que la misma organización (concejalía, departamento, etc.) actúe como entidadFinanciadora y gestionadoPor. Eso no es problema si tiene sentido.
En el caso del tieneBeneficiario, este puede ser cualquier tipo de organización, entendida de forma muy general (asociación, fundación, empresa, autónomos, personas físicas, etc.), que normalmente estarán en vuestras bases de datos de terceros y/o ciudadanos.
