### ISSUE TITLE
Proyecto

### ISSUE THREAD

**Issue by runobe** [opencitydata/vocab-sector-publico-subvenciones#12]
En el modelo de datos figura asociada a la subvención el campo proyecto 
En la práctica ese campo al menos nosotros lo tenemos vinculado más a la concesión. Entendiendo que cada beneficiario propone un proyecto para esa convocatoria si hay más de una propuesta va a existir más de un proyecto.
ejemplo: https://www.zaragoza.es/ciudad/gestionmunicipal/ayudasysubvenciones/detalleConv_AyudasSubvenciones?id=600
quizás ese atributo se debería de trasladar a la relación subvencion_beneficiario

**Comment by fyedro** [comment]
Creado un nuevo issue #15 para tratarlo como bug, se dará respuesta a través de dicho issue
