### ISSUE TITLE
Año de la convocatoria

### ISSUE THREAD

**Issue by runobe** [opencitydata/vocab-sector-publico-subvenciones#13]
Anticipándome al nuevo modelo de datos en la presentación del viernes creo que sobre convocatoria solo existe el campo fecha de aprobación campo que nosotros en nuestro modelo de datos no tenemos y que no es obligatorio en el actual modelo.
No sería aconsejable añadir un nuevo atributo Ejercicio/año, de carácter obligatorio, para reflejar de que año es la convocatoria? Ese campo si que nosotros lo tenemos y creo que es altamente probable que lo tengamos todos, creo que lo debe de marcar la bbdd de subvenciones del ministerio, porque sin ese campo cómo se puede determinar en el servicio de visualización que una convocatoria es de un año determinado?

**Comment by ocorcho** [comment]
Se añadirá a Convocatoria el atributo espresup:anioFiscal, ya definido en el vocabulario de presupuestos.

**Comment by fyedro** [comment]
Atributo añadido en la última versión del modelo
