### ISSUE TITLE
Dónde indicar la aplicación presupuestaria (concesión y/o convocatoria)

### ISSUE THREAD

**Issue by fyedro** [opencitydata/vocab-sector-publico-subvenciones#17]
Se necesita confirmar con los ayuntamientos si las propiedades relacionadas con la aplicación presupuestaria (clasificación económica de gasto y programa de gasto) son únicamente aplicables a las convocatorias (como suele aparecer en los textos de las convocatorias), únicamente aplicables a las concesiones (como aparece en la Base de Datos Nacional de Subvenciones), o son aplicables tanto a convocatorias como concesiones, para permitir la mayor flexibilidad en el modelo de datos. 

También hay que confirmar las cardinalidades de estas relaciones, si tienen que ser (0..n) o (0..1). Es decir, se consideran propiedades opcionales, en caso de que no se tenga esta información de aplicación presupuestaria, pero queremos confirmar si sólo puede haber una aplicación presupuestaria asociada a una Convocatoria/Concesión, o pueden ser varias, como se adelantó en una conversación por videoconferencia.

A continuación incluimos algunas imágenes en las que se muestra cómo el texto de una convocatoria publicado en un boletín oficial contiene la referencia a la aplicación presupuestaria, pero al mismo tiempo para esa misma convocatoria y sus concesiones esta información aparece asociada a las concesiones

![convocatorias](https://github.com/opencitydata/vocab-sector-publico-subvenciones/raw/main/images/resultado_busqueda_convocatorias.png)

En la BDNS, la Aplicación presupuestaria no está en convocatorias sino en concesiones:

![concesiones](https://github.com/opencitydata/vocab-sector-publico-subvenciones/raw/main/images/resultado_busqueda_concesiones.png)

Ejemplo de un documento de una convocatoria contiene la aplicación presupuestaria:

![concesiones](https://github.com/opencitydata/vocab-sector-publico-subvenciones/raw/main/images/doc_concesiones.png)

**Comment by ocorcho** [comment]
@fyedro Añade las imágenes, para poder enviar correo electrónico a todos para solicitar feedback

**Comment by fyedro** [comment]
![convocatorias](https://github.com/opencitydata/vocab-sector-publico-subvenciones/blob/main/images/resultado_busqueda_convocatorias.png)

En la BDNS, la Aplicación presupuestaria no está en convocatorias sino en concesiones:

![concesiones](https://github.com/opencitydata/vocab-sector-publico-subvenciones/blob/main/images/resultado_busqueda_concesiones.png)

**Comment by runobe** [comment]
Hola, la información relativa a las aplicaciones presupuestarias en el caso de Zaragoza son aplicables tanto a las concesiones como a convocatorias y tanto para concesiones como para convocatorias pueden tener asignadas varias aplicaciones presupuestarias. Lo que ya no tengo claro es el grado de detalle que se debe llegar igual solo con asociarlo a una de ellas concesiones quizás en este caso sea suficiente. 
Os pongo captura de los datos que disponemos, nos han dado acceso hoy, 
así para **convocatorias**:
``
![convocatorias](https://user-images.githubusercontent.com/11404634/108504118-b2d6ca00-72b5-11eb-9c1f-2168295861ef.png)

Y para **concesiones**:
![concesiones](https://user-images.githubusercontent.com/11404634/108504274-e7e31c80-72b5-11eb-9e1a-599d6e5d9b2e.png)

**Comment by crmoreno** [comment]
Hola, En el Ayuntamiento de Madrid tenemos la siguiente respuesta.
 "En el módulo SAP de subvenciones convocatorias pueden tener una o más de una aplicación presupuestaria pero nosotros para esta extracción quedamos con en que solo mostrábamos una aplicación y las concesiones pues lo mismo."
Para que el modelo sea correcto, en mi opinión, hay que contar con la posibilidad de que haya más de una aplicación presupuestaria tanto para concesiones como para convocatorias. Es cierto que no tenemos ningún ejemplo, lo vamos a pedir.
Con las especificaciones para el modelo extendido lo tendremos en cuenta.
Por cierto, ¿habéis encontrado algún ejemplo en la BDNS en que haya concesiones con más de una aplicación presupuestaria? 
Saludos,

**Comment by crmoreno** [comment]
Otra información complementaria a lo anterior:
"He encontrado una convocatoria con dos aplicaciones, pero en este caso no influye que tenga dos aplicaciones en la información que exportamos ya que internamente a la BDNS se envía como 2 convocatorias distintas y cada aplicación de concesión a su convocatoria correspondiente y así en la extracción. A la BDNS solo se manda la aplicación en las concesiones"

**Comment by ocorcho** [comment]
Muchas gracias. 

Entonces queda claro, por toda la conversación, que lo más general será:
- Permitir asociar a las convocatorias de subvención una o más aplicaciones presupuestarias (pondremos cardinalidad 0..N). El 0 nos permitirá que cuando se cargue de la BDNS no haya valores. 
- Permitir asociar a cada concesión de subvención una o más aplicaciones presupuestarias (pondremos también cardinalidad 0..N). Si se trata como en el caso de Madrid, será realmente una relación 0..1, pero si se trata como en el caso de Zaragoza será 0..N. Por esta razón, nos quedamos con lo más general.

Dado que es la solución más general, servirá para el resto de ciudades también. @fyedro puedes ya cerrar el modelo conceptual con esto, y así cerramos este y los demás issues que ya estaban pre-tratados.

**Comment by fyedro** [comment]
Modificado el diseño según las necesidades descritas. Hasta la publicación definitiva, se puede consultar la documentación en:
https://opencitydata.github.io/vocab-sector-publico-subvenciones/docs/index-es.html
