### ISSUE TITLE
Error en la documentación

### ISSUE THREAD

**Issue by hlafuente** [opencitydata/vocab-sector-publico-subvenciones#20]
En el fichero (vocab-sector-publico-subvenciones/docs/sections/description-es.html) para el ejemplo de concesión, está tipado como una convocatoria.

 
 <http://vocab.ciudadesabiertas.es/recurso/sector-publico/subvencion/concesion/1523> a essubv:Convocatoria ;
  dct:identifier "con1523" ;
```

**Comment by fyedro** [comment]
Error en documentación corregido a:
<http://vocab.ciudadesabiertas.es/recurso/sector-publico/subvencion/concesion/1523> a essubv:Concesion ;
  dct:identifier "con1523" ;
